### ISSUE TITLE
Exception in plugin Dummy Text Generator 

### ISSUE THREAD

**Issue by jaroslav-kesel** [kstenschke/dummytext-plugin#13]
After starting PHP Storm (2024.1) an error is displayed.
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.kstenschke.dummytext.Action' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: Dummy Text Generator]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```
Is it possible to look into it and fix it?
Thanks.

**Comment by jaroslav-kesel** [comment]
The problem was fixed in the PHPstorm app.
